/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AhuAhuIdRouteImport } from './routes/ahu/$ahuId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AhuAhuIdRoute = AhuAhuIdRouteImport.update({
  id: '/ahu/$ahuId',
  path: '/ahu/$ahuId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ahu/$ahuId': typeof AhuAhuIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ahu/$ahuId': typeof AhuAhuIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ahu/$ahuId': typeof AhuAhuIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ahu/$ahuId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ahu/$ahuId'
  id: '__root__' | '/' | '/ahu/$ahuId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AhuAhuIdRoute: typeof AhuAhuIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ahu/$ahuId': {
      id: '/ahu/$ahuId'
      path: '/ahu/$ahuId'
      fullPath: '/ahu/$ahuId'
      preLoaderRoute: typeof AhuAhuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AhuAhuIdRoute: AhuAhuIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
